# Generated by Django 3.1.1 on 2021-06-01 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20210601_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='legal_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='admin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.company'),
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='core.department'),
            preserve_default=False,
        ),
    ]
